// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlpJS9IsYRYJRdf5Rz74lRqlX23LDumEA',
    appId: '1:876226260622:web:546e3d29340250c4b963df',
    messagingSenderId: '876226260622',
    projectId: 'flutter-with-firebase-99bc7',
    authDomain: 'flutter-with-firebase-99bc7.firebaseapp.com',
    storageBucket: 'flutter-with-firebase-99bc7.firebasestorage.app',
    measurementId: 'G-QKR352F66B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj4vuVR1hsyB83Q-BpEsoUYoSREUluccM',
    appId: '1:876226260622:android:773da9e9079b7993b963df',
    messagingSenderId: '876226260622',
    projectId: 'flutter-with-firebase-99bc7',
    storageBucket: 'flutter-with-firebase-99bc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmOsvHWChOuCuDdiwl5_vtm23Epy433A4',
    appId: '1:876226260622:ios:2d7c2d3540e9ab43b963df',
    messagingSenderId: '876226260622',
    projectId: 'flutter-with-firebase-99bc7',
    storageBucket: 'flutter-with-firebase-99bc7.firebasestorage.app',
    iosBundleId: 'com.example.flutterWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmOsvHWChOuCuDdiwl5_vtm23Epy433A4',
    appId: '1:876226260622:ios:2d7c2d3540e9ab43b963df',
    messagingSenderId: '876226260622',
    projectId: 'flutter-with-firebase-99bc7',
    storageBucket: 'flutter-with-firebase-99bc7.firebasestorage.app',
    iosBundleId: 'com.example.flutterWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlpJS9IsYRYJRdf5Rz74lRqlX23LDumEA',
    appId: '1:876226260622:web:d572ab05a2c43fa9b963df',
    messagingSenderId: '876226260622',
    projectId: 'flutter-with-firebase-99bc7',
    authDomain: 'flutter-with-firebase-99bc7.firebaseapp.com',
    storageBucket: 'flutter-with-firebase-99bc7.firebasestorage.app',
    measurementId: 'G-LKHL5QYS7B',
  );
}
